# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            form_login:
              login_path: login
              check_path: login
              default_target_path: 'home'
            logout:
              path: /logout
              target: /    
       
    access_control:
      - { path: ^/admin/*, roles: ROLE_ADMIN }      
      - { path: ^/(|login), roles: IS_AUTHENTICATED_ANONYMOUSLY }
      
    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
